GET http://localhost:3000/pokemon/


###
GET http://localhost:3000/pokemon/6977b822e1139b3a057d43f3


###
POST http://localhost:3000/pokemon HTTP/1.1
content-type: application/json

{
  "pokemon": "Pichu",
  "types": "Electric",
  "evolution": "Pikachu",
  "level": "4",
  "nature": "timid"
}


###
PUT http://localhost:3000/pokemon/6977b822e1139b3a057d43f3/ HTTP/1.1
Content-Type: application/json

{
    "pokemon":"Pikachu",
    "types":"Electric",
    "evolution":"Raichu",
    "level":"10",
    "nature":"Slow"
}


###
DELETE http://localhost:3000/pokemon/6977b822e1139b3a057d43f3 HTTP/1.1
Content-Type: application/json